version: '3'

services:
  maesbot:
    build: .
    container_name: maesbot
    volumes:
      - .:/app
      - ${HOME}:/home/user
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
    tty: true
    stdin_open: true
