baseurl: "" # when not using a custom domain, use this base url: /meneermaes

# how should the url's be generated
# permalink: /:path/:basename/

# default file settings
defaults:
  - scope:
      path: "" # empty string means all files
    values:
      layout: default # make default the layout of all files not specifying a layout in the front matter