# Base URL and Custom Domain
baseurl: "" # Leave empty when using a custom domain, otherwise specify your base URL (e.g., "/meneermaes")

# URL Generation
# permalink: /:path/:basename/ # Uncomment and set if you want to customize permalinks

# Default File Settings
defaults:
  - scope:
      path: "" # Empty string means all files
    values:
      layout: default # Apply the 'default' layout to all files not specifying a layout in the front matter